version: '2'

services:

 https-portal:
  image: steveltn/https-portal
  links:
   - mattermost-web
  ports:
  # - "80:80"
    - "443:443"
  restart: always
  volumes:
   - data-https:/var/lib/https-portal/
   - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - IP_ADDRESS=11.22.33.44
    - DOMAINS=mattermost.${IP_ADDRESS}.xip.io -> http://mattermost-web
    # - STAGE="production"
    # - FORCE_RENEW="true"

 mattermost-db:
  image: mattermost/mattermost-prod-db
  hostname: db
  volumes:
    - data-mattermost-data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro

 mattermost-app:
  image: mattermost/mattermost-prod-app
  hostname: app
  links:
    - mattermost-db:db
  volumes:
    - data-mattermost-config:/mattermost/config:rw
    - data-mattermost-data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro

 mattermost-web:
  image: mattermost/mattermost-prod-web
  hostname: web
  ports:
    - 80
    - 443
  links:
    - mattermost-app:app
  volumes:
    - data-mattermost-certs:/cert:ro
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MATTERMOST_ENABLE_SSL=false
    - PLATFORM_PORT_80_TCP_PORT=80

volumes:
 data-https:
 data-mattermost-data:
 data-mattermost-config:
 data-mattermost-certs:
